[sncast.default]
url = "http://localhost:5050/rpc"
accounts-file = "accounts.json"
account = "devnet0"
show-explorer-links = false

[sncast.sepolia]
chain_id = "SN_SEPOLIA"
#url = "https://starknet-sepolia.public.blastapi.io"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_8/hWvw1XMZRZY4oNd6EvHgk"
accounts-file = "accounts.json"
account = "jw-strk-t2"
show-explorer-links = true
